import Link from 'next/link';
import {
  Zap,
  Check,
  Clock,
  FileX,
  Wallet,
  Layout,
  Share2,
  ShieldCheck,
  Mic,
  Image as ImageIcon,
  Mail,
  CheckCircle2,
  PlayCircle,
  ArrowRight,
  XCircle,
  Scale,
  Stethoscope,
  Home,
  Briefcase,
  Dumbbell,
} from 'lucide-react';

export default function MarketingSite() {
  return (
    <div className="min-h-screen">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-purple-600 rounded-md flex items-center justify-center text-white">
                <Zap className="w-5 h-5" />
              </div>
              <span className="font-bold text-xl text-slate-900">PulseAgent</span>
            </div>
            <div className="hidden md:flex items-center space-x-8">
              <a href="#how-it-works" className="text-slate-600 hover:text-purple-600 font-medium transition-colors">
                How it Works
              </a>
              <a href="#features" className="text-slate-600 hover:text-purple-600 font-medium transition-colors">
                Features
              </a>
              <a href="#pricing" className="text-slate-600 hover:text-purple-600 font-medium transition-colors">
                Pricing
              </a>
              <a href="#faq" className="text-slate-600 hover:text-purple-600 font-medium transition-colors">
                FAQ
              </a>
            </div>
            <div className="flex items-center gap-4">
              <Link href="/login" className="hidden sm:block text-slate-900 font-medium hover:text-purple-600">
                Login
              </Link>
              <Link
                href="/signup"
                className="bg-purple-600 hover:bg-purple-700 text-white px-5 py-2 rounded-md font-medium transition-all shadow-md hover:shadow-lg"
              >
                Start Free Trial
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-20 pb-32 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-slate-50 via-white to-purple-50 -z-10"></div>
        <div className="absolute top-0 right-0 w-1/3 h-1/3 bg-purple-200 rounded-full blur-3xl opacity-20 translate-x-1/2 -translate-y-1/2"></div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-100 text-purple-700 font-medium text-sm mb-8 border border-purple-200">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-purple-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-purple-500"></span>
            </span>
            Now with Claude 3.5 Sonnet & DALL-E 3
          </div>

          <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-slate-900 tracking-tight mb-6 leading-tight">
            Your Digital Marketing Team.
            <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-teal-500">
              Automated.
            </span>
          </h1>

          <p className="text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
            A full digital marketing team in a box. 30-150 social posts per month, generated by AI, posted by you in 30
            seconds a day.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <a
              href="#pricing"
              className="w-full sm:w-auto px-8 py-4 bg-purple-600 hover:bg-purple-700 text-white text-lg font-semibold rounded-md shadow-md hover:shadow-lg transition-all flex items-center justify-center gap-2"
            >
              Start Your Free Trial <ArrowRight className="w-5 h-5" />
            </a>
            <a
              href="#how-it-works"
              className="w-full sm:w-auto px-8 py-4 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 text-lg font-semibold rounded-md shadow-sm transition-all flex items-center justify-center gap-2"
            >
              <PlayCircle className="w-5 h-5" /> See How It Works
            </a>
          </div>

          {/* Hero Visual */}
          <div className="relative mx-auto max-w-5xl">
            <div className="absolute -inset-1 bg-gradient-to-r from-purple-500 to-teal-500 rounded-lg blur opacity-20"></div>
            <div className="relative bg-white rounded-lg shadow-2xl border border-slate-200 overflow-hidden">
              <div className="grid md:grid-cols-2 gap-0">
                <div className="p-8 md:p-12 flex flex-col justify-center text-left bg-slate-50 border-r border-slate-100">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center text-green-600">
                      <Check className="w-6 h-6" />
                    </div>
                    <div>
                      <p className="text-sm text-slate-500 font-medium">Daily Task</p>
                      <p className="font-bold text-slate-900">Post Ready for Review</p>
                    </div>
                  </div>
                  <div className="space-y-4">
                    <div className="bg-white p-4 rounded-md shadow-sm border border-slate-200">
                      <div className="flex items-center gap-3 mb-3">
                        <img
                          src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=100&h=100"
                          alt="User"
                          className="w-10 h-10 rounded-full object-cover"
                        />
                        <div>
                          <p className="font-bold text-sm">Dr. Sarah Miller</p>
                          <p className="text-xs text-slate-500">Chiropractor • Just now</p>
                        </div>
                      </div>
                      <p className="text-slate-700 text-sm mb-3">
                        Did you know that poor posture can lead to chronic fatigue? Here are 3 simple stretches you can
                        do at your desk today to boost energy levels. #ChiropracticCare #Wellness #OfficeHealth
                      </p>
                      <div className="aspect-video bg-slate-100 rounded-md overflow-hidden">
                        <img
                          src="https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80"
                          alt="Post Image"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                    <button className="w-full py-2 bg-purple-600 text-white rounded-md font-medium text-sm hover:bg-purple-700 transition-colors">
                      Approve & Post (1-Click)
                    </button>
                  </div>
                </div>
                <div className="p-8 md:p-12 bg-white flex flex-col justify-center">
                  <h3 className="text-2xl font-bold mb-4">Wake up to done-for-you content.</h3>
                  <ul className="space-y-4">
                    <li className="flex items-start gap-3">
                      <CheckCircle2 className="w-6 h-6 text-purple-600 shrink-0 mt-0.5" />
                      <span className="text-slate-600">
                        <strong>8:00 AM Delivery:</strong> Your daily post arrives in your inbox.
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <CheckCircle2 className="w-6 h-6 text-purple-600 shrink-0 mt-0.5" />
                      <span className="text-slate-600">
                        <strong>Industry Specific:</strong> Trained on your niche (Legal, Medical, Finance).
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <CheckCircle2 className="w-6 h-6 text-purple-600 shrink-0 mt-0.5" />
                      <span className="text-slate-600">
                        <strong>Platform Optimized:</strong> Formatted perfectly for LinkedIn, IG, FB, and X.
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-12 bg-white border-y border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-center text-slate-500 font-medium mb-8">TRUSTED BY PROFESSIONALS IN</p>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-8 items-center opacity-60 grayscale hover:grayscale-0 transition-all duration-500">
            <div className="flex flex-col items-center gap-2">
              <Scale className="w-8 h-8 text-slate-800" />
              <span className="font-bold text-slate-800">Law Firms</span>
            </div>
            <div className="flex flex-col items-center gap-2">
              <Stethoscope className="w-8 h-8 text-slate-800" />
              <span className="font-bold text-slate-800">Healthcare</span>
            </div>
            <div className="flex flex-col items-center gap-2">
              <Home className="w-8 h-8 text-slate-800" />
              <span className="font-bold text-slate-800">Real Estate</span>
            </div>
            <div className="flex flex-col items-center gap-2">
              <Briefcase className="w-8 h-8 text-slate-800" />
              <span className="font-bold text-slate-800">Insurance</span>
            </div>
            <div className="flex flex-col items-center gap-2">
              <Dumbbell className="w-8 h-8 text-slate-800" />
              <span className="font-bold text-slate-800">Fitness</span>
            </div>
          </div>
        </div>
      </section>

      {/* Problem Section */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
              You're too busy running your business to post on social media.
            </h2>
            <p className="text-lg text-slate-600">We get it. Marketing is a full-time job, but you already have one.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-lg shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center text-red-600 mb-6">
                <Clock className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">"I don't have time"</h3>
              <p className="text-slate-600">
                Creating content takes hours you don't have. You're focused on clients, not captions.
              </p>
            </div>
            <div className="bg-white p-8 rounded-lg shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center text-orange-600 mb-6">
                <FileX className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">"I don't know what to post"</h3>
              <p className="text-slate-600">
                Staring at a blank screen is painful. Writer's block kills your consistency before you even start.
              </p>
            </div>
            <div className="bg-white p-8 rounded-lg shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 mb-6">
                <Wallet className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">"Agencies are expensive"</h3>
              <p className="text-slate-600">
                Hiring a marketing team costs $150k+/year. Even a basic freelancer is $2k/month.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-24 bg-white overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-20">
            <span className="text-purple-600 font-bold tracking-wider uppercase text-sm">The Process</span>
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mt-2">
              What if content just... appeared?
            </h2>
          </div>

          <div className="relative">
            {/* Connecting Line (Desktop) */}
            <div className="hidden md:block absolute top-1/2 left-0 w-full h-0.5 bg-slate-100 -translate-y-1/2 z-0"></div>

            <div className="grid md:grid-cols-4 gap-8 relative z-10">
              {/* Step 1 */}
              <div className="bg-white p-6 rounded-lg border border-slate-100 shadow-md text-center group hover:-translate-y-1 transition-transform duration-300">
                <div className="w-16 h-16 mx-auto bg-slate-900 text-white rounded-full flex items-center justify-center text-2xl font-bold mb-6 shadow-lg group-hover:bg-purple-600 transition-colors">
                  1
                </div>
                <h3 className="text-lg font-bold mb-2">5-Minute Setup</h3>
                <p className="text-slate-600 text-sm">
                  Tell us your business, industry, and target audience. Select your platforms.
                </p>
              </div>

              {/* Step 2 */}
              <div className="bg-white p-6 rounded-lg border border-slate-100 shadow-md text-center group hover:-translate-y-1 transition-transform duration-300">
                <div className="w-16 h-16 mx-auto bg-slate-900 text-white rounded-full flex items-center justify-center text-2xl font-bold mb-6 shadow-lg group-hover:bg-purple-600 transition-colors">
                  2
                </div>
                <h3 className="text-lg font-bold mb-2">AI Does The Work</h3>
                <p className="text-slate-600 text-sm">
                  We generate 30-150 posts, create images, and schedule everything for the month.
                </p>
              </div>

              {/* Step 3 */}
              <div className="bg-white p-6 rounded-lg border border-slate-100 shadow-md text-center group hover:-translate-y-1 transition-transform duration-300">
                <div className="w-16 h-16 mx-auto bg-slate-900 text-white rounded-full flex items-center justify-center text-2xl font-bold mb-6 shadow-lg group-hover:bg-purple-600 transition-colors">
                  3
                </div>
                <h3 className="text-lg font-bold mb-2">Daily Email</h3>
                <p className="text-slate-600 text-sm">
                  Wake up to an email at 8am with your post, image, and hashtags ready to go.
                </p>
              </div>

              {/* Step 4 */}
              <div className="bg-white p-6 rounded-lg border border-slate-100 shadow-md text-center group hover:-translate-y-1 transition-transform duration-300">
                <div className="w-16 h-16 mx-auto bg-slate-900 text-white rounded-full flex items-center justify-center text-2xl font-bold mb-6 shadow-lg group-hover:bg-purple-600 transition-colors">
                  4
                </div>
                <h3 className="text-lg font-bold mb-2">30-Second Post</h3>
                <p className="text-slate-600 text-sm">
                  Copy, paste, and post. Or use our one-click share buttons. Done for the day.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-24 bg-slate-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Everything you need to dominate your market</h2>
            <p className="text-slate-400 text-lg">Replaces a $150k marketing team for a fraction of the cost.</p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="bg-slate-800 p-8 rounded-lg border border-slate-700 hover:border-purple-500 transition-colors">
              <Layout className="w-10 h-10 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold mb-3">AI Landing Pages</h3>
              <p className="text-slate-400">
                Professional landing pages created in 60 seconds. Replace expensive websites with high-converting pages
                for services and offers.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-slate-800 p-8 rounded-lg border border-slate-700 hover:border-purple-500 transition-colors">
              <Share2 className="w-10 h-10 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold mb-3">Multi-Platform Social</h3>
              <p className="text-slate-400">
                Content for LinkedIn, Facebook, Instagram, X (Twitter), and YouTube. Formatted perfectly for each
                platform.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-slate-800 p-8 rounded-lg border border-slate-700 hover:border-purple-500 transition-colors">
              <ShieldCheck className="w-10 h-10 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold mb-3">Safety & Moderation</h3>
              <p className="text-slate-400">
                OpenAI Moderation API screens every post. Brand-safe, compliant content for regulated industries like
                law and finance.
              </p>
            </div>

            {/* Feature 4 */}
            <div className="bg-slate-800 p-8 rounded-lg border border-slate-700 hover:border-purple-500 transition-colors">
              <Mic className="w-10 h-10 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold mb-3">Podcast Scripts</h3>
              <p className="text-slate-400">
                Complete episode outlines, intros, and show notes generated weekly. Build authority without the prep
                work.
              </p>
            </div>

            {/* Feature 5 */}
            <div className="bg-slate-800 p-8 rounded-lg border border-slate-700 hover:border-purple-500 transition-colors">
              <ImageIcon className="w-10 h-10 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold mb-3">Custom AI Images</h3>
              <p className="text-slate-400">
                No more stock photos. We generate unique, platform-specific images for every single post using DALL-E 3.
              </p>
            </div>

            {/* Feature 6 */}
            <div className="bg-slate-800 p-8 rounded-lg border border-slate-700 hover:border-purple-500 transition-colors">
              <Mail className="w-10 h-10 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold mb-3">Daily Delivery</h3>
              <p className="text-slate-400">
                Content delivered to your inbox at 8am local time. Review, approve, and post in seconds.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ROI Section */}
      <section className="py-24 bg-purple-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-lg shadow-xl overflow-hidden border border-slate-200">
            <div className="grid md:grid-cols-2">
              <div className="p-12 bg-slate-900 text-white flex flex-col justify-center">
                <h3 className="text-3xl font-bold mb-6">Traditional Marketing Team</h3>
                <div className="space-y-4 mb-8">
                  <div className="flex justify-between items-center border-b border-slate-700 pb-2">
                    <span>Social Media Manager</span>
                    <span className="font-mono text-slate-400">$50,000/yr</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-slate-700 pb-2">
                    <span>Content Writer</span>
                    <span className="font-mono text-slate-400">$60,000/yr</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-slate-700 pb-2">
                    <span>Graphic Designer</span>
                    <span className="font-mono text-slate-400">$55,000/yr</span>
                  </div>
                  <div className="flex justify-between items-center pt-2 text-xl font-bold text-red-400">
                    <span>Total Cost</span>
                    <span>$165,000/yr</span>
                  </div>
                </div>
                <div className="flex items-center gap-2 text-red-300">
                  <XCircle className="w-5 h-5" />
                  <span>Expensive, slow hiring, management headaches</span>
                </div>
              </div>

              <div className="p-12 bg-white flex flex-col justify-center relative overflow-hidden">
                <div className="absolute top-0 right-0 bg-purple-500 text-white text-xs font-bold px-3 py-1 rounded-bl-lg">
                  97% SAVINGS
                </div>
                <h3 className="text-3xl font-bold mb-6 text-purple-700">PulseAgent Pro</h3>
                <div className="space-y-4 mb-8">
                  <div className="flex justify-between items-center border-b border-slate-100 pb-2">
                    <span className="text-slate-600">AI Content Writer</span>
                    <span className="font-mono text-purple-600 font-bold">Included</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-slate-100 pb-2">
                    <span className="text-slate-600">AI Graphic Designer</span>
                    <span className="font-mono text-purple-600 font-bold">Included</span>
                  </div>
                  <div className="flex justify-between items-center border-b border-slate-100 pb-2">
                    <span className="text-slate-600">Social Media Strategy</span>
                    <span className="font-mono text-purple-600 font-bold">Included</span>
                  </div>
                  <div className="flex justify-between items-center pt-2 text-xl font-bold text-purple-600">
                    <span>Total Cost</span>
                    <span>$3,588/yr</span>
                  </div>
                </div>
                <div className="flex items-center gap-2 text-green-600 font-medium">
                  <CheckCircle2 className="w-5 h-5" />
                  <span>Instant setup, consistent quality, zero management</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Simple, Transparent Pricing</h2>
            <p className="text-slate-600 text-lg">Choose the level of automation that fits your business stage.</p>
          </div>

          <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
            {/* Starter */}
            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm hover:shadow-lg transition-shadow flex flex-col">
              <div className="mb-4">
                <h3 className="text-xl font-bold text-slate-900">Starter</h3>
                <p className="text-sm text-slate-500 mt-1">For solo practitioners</p>
              </div>
              <div className="mb-6">
                <span className="text-4xl font-bold text-slate-900">$79</span>
                <span className="text-slate-500">/mo</span>
                <p className="text-xs text-slate-400 mt-2">+$297 one-time setup</p>
              </div>
              <ul className="space-y-3 mb-8 flex-1">
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 30 posts/platform
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 2 Social Platforms
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 3 Landing Pages
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> Daily Email Delivery
                </li>
              </ul>
              <Link
                href="/signup"
                className="w-full py-3 border border-purple-600 text-purple-600 font-bold rounded-md text-center hover:bg-purple-50 transition-colors"
              >
                Get Started
              </Link>
            </div>

            {/* Growth */}
            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm hover:shadow-lg transition-shadow flex flex-col">
              <div className="mb-4">
                <h3 className="text-xl font-bold text-slate-900">Growth</h3>
                <p className="text-sm text-slate-500 mt-1">For growing businesses</p>
              </div>
              <div className="mb-6">
                <span className="text-4xl font-bold text-slate-900">$129</span>
                <span className="text-slate-500">/mo</span>
                <p className="text-xs text-slate-400 mt-2">+$497 one-time setup</p>
              </div>
              <ul className="space-y-3 mb-8 flex-1">
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 50 posts/platform
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 3 Social Platforms
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 5 Landing Pages
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> Content Moderation
                </li>
              </ul>
              <Link
                href="/signup"
                className="w-full py-3 border border-purple-600 text-purple-600 font-bold rounded-md text-center hover:bg-purple-50 transition-colors"
              >
                Get Started
              </Link>
            </div>

            {/* Pro */}
            <div className="bg-slate-900 p-6 rounded-lg border border-purple-500 shadow-xl relative flex flex-col transform md:-translate-y-4">
              <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-purple-500 text-white px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide">
                Most Popular
              </div>
              <div className="mb-4">
                <h3 className="text-xl font-bold text-white">Pro</h3>
                <p className="text-sm text-slate-400 mt-1">For serious authority</p>
              </div>
              <div className="mb-6">
                <span className="text-4xl font-bold text-white">$299</span>
                <span className="text-slate-400">/mo</span>
                <p className="text-xs text-slate-500 mt-2">+$697 one-time setup</p>
              </div>
              <ul className="space-y-3 mb-8 flex-1">
                <li className="flex items-start gap-2 text-sm text-slate-300">
                  <Check className="w-4 h-4 text-purple-400 mt-0.5 shrink-0" /> 150 posts/platform
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-300">
                  <Check className="w-4 h-4 text-purple-400 mt-0.5 shrink-0" /> 5 Social Platforms
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-300">
                  <Check className="w-4 h-4 text-purple-400 mt-0.5 shrink-0" /> 10 Landing Pages
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-300">
                  <Check className="w-4 h-4 text-purple-400 mt-0.5 shrink-0" /> Weekly Podcast Scripts
                </li>
              </ul>
              <Link
                href="/signup"
                className="w-full py-3 bg-purple-600 text-white font-bold rounded-md text-center hover:bg-purple-700 transition-colors shadow-lg"
              >
                Get Started
              </Link>
            </div>

            {/* Authority */}
            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm hover:shadow-lg transition-shadow flex flex-col">
              <div className="mb-4">
                <h3 className="text-xl font-bold text-slate-900">Authority</h3>
                <p className="text-sm text-slate-500 mt-1">Market leaders</p>
              </div>
              <div className="mb-6">
                <span className="text-4xl font-bold text-slate-900">$499</span>
                <span className="text-slate-500">/mo</span>
                <p className="text-xs text-slate-400 mt-2">+$997 one-time setup</p>
              </div>
              <ul className="space-y-3 mb-8 flex-1">
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> 150 posts/platform
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> All 5 Platforms + YT
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> Unlimited Landing Pages
                </li>
                <li className="flex items-start gap-2 text-sm text-slate-600">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" /> YouTube Video Content
                </li>
              </ul>
              <Link
                href="/signup"
                className="w-full py-3 border border-purple-600 text-purple-600 font-bold rounded-md text-center hover:bg-purple-50 transition-colors"
              >
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-24 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Common Questions</h2>
            <p className="text-slate-600">Doubts about AI? Let's clear them up.</p>
          </div>

          <div className="space-y-6">
            <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
              <h3 className="text-lg font-bold text-slate-900 mb-2">
                "AI content sounds robotic. Will this sound like me?"
              </h3>
              <p className="text-slate-600">
                Our AI is trained on your specific industry and uses your brand voice (professional, friendly, bold,
                etc.). Plus, you review every post before it goes live. If something feels off, don't post it.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
              <h3 className="text-lg font-bold text-slate-900 mb-2">"What if the AI makes a mistake?"</h3>
              <p className="text-slate-600">
                Every piece of content goes through OpenAI's moderation API. New clients get manual review for the first
                30 days. Nothing goes to your audience without you approving it first.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
              <h3 className="text-lg font-bold text-slate-900 mb-2">"I don't have time to post every day."</h3>
              <p className="text-slate-600">
                Each post takes 30 seconds: Open email → Copy → Paste → Post. That's it. Less time than making coffee.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
              <h3 className="text-lg font-bold text-slate-900 mb-2">
                "My industry is highly regulated (Legal/Finance)."
              </h3>
              <p className="text-slate-600">
                We support legal, healthcare, and financial services. The AI is trained on industry-specific language
                and compliance rules to ensure safety.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 bg-slate-900 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-purple-900 to-slate-900 z-0"></div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">Ready to automate your marketing?</h2>
          <p className="text-xl text-slate-300 mb-10">
            Join 500+ businesses growing their digital presence on autopilot.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/signup"
              className="w-full sm:w-auto px-8 py-4 bg-purple-600 hover:bg-purple-500 text-white text-lg font-bold rounded-md shadow-lg transition-all"
            >
              Start Your Free Trial
            </Link>
            <p className="text-slate-400 text-sm mt-4 sm:mt-0 sm:ml-4">No credit card required. Cancel anytime.</p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-950 text-slate-400 py-12 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div className="col-span-1 md:col-span-2">
              <div className="flex items-center gap-2 mb-4 text-white">
                <Zap className="w-6 h-6 text-purple-500" />
                <span className="font-bold text-xl">PulseAgent</span>
              </div>
              <p className="max-w-xs text-sm">
                The AI-powered Done-For-You Digital Presence Platform for local businesses.
              </p>
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Product</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <a href="#features" className="hover:text-white transition-colors">
                    Features
                  </a>
                </li>
                <li>
                  <a href="#pricing" className="hover:text-white transition-colors">
                    Pricing
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Success Stories
                  </a>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Company</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    About Us
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Contact
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Privacy Policy
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className="border-t border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs">
            <p>© 2024 PulseAgent. All rights reserved.</p>
            <div className="flex gap-4">
              <a href="#" className="hover:text-white text-sm">
                X
              </a>
              <a href="#" className="hover:text-white text-sm">
                LinkedIn
              </a>
              <a href="#" className="hover:text-white text-sm">
                Facebook
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
